### ISSUE TITLE
Initial values incorrect?

### ISSUE THREAD

**Issue by EmJay276** [mechmotum/cyipopt#173] opened 2022-12-20 16:54 UTC
I build a quite complicated NLP using the Problem interface ( https://cyipopt.readthedocs.io/en/stable/tutorial.html#problem-interface ), which is working fine.

I am using a lot of class variables within the Problem class.

But I noticed a strange initial behaviour where the initial objective (and constraints) are wrong evaluated, see blow.

Initial objective / constraints values (from a previous optimization) when i manually evaluate them
```
>>> prob.objective(x0)
4974321.999640268
```
EQ constraints == 0
```
>>> np.abs(prob.constraints(x0)[:prob.n_eq_constr]).max()
5.045876605436206e-09
```
INEQ constraints > 0
```
>>> prob.constraints(x0)[prob.n_eq_constr:].min()
-1.328551330130685e-06
```

When using the solve method, the initial values are off by a factor of 52 (objective) and 1e8 (constraints)

```
x, info = nlp.solve(x0)
This is Ipopt version 3.14.10, running with linear solver MUMPS 5.2.1.
Number of nonzeros in equality constraint Jacobian...:    10692
Number of nonzeros in inequality constraint Jacobian.:     3576
Number of nonzeros in Lagrangian Hessian.............:     5185
Total number of variables............................:     1582
                     variables with only lower bounds:      447
                variables with lower and upper bounds:      241
                     variables with only upper bounds:        0
Total number of equality constraints.................:      510
Total number of inequality constraints...............:     1788
        inequality constraints with only lower bounds:     1788
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.5866283e+08 3.49e+01 1.90e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
Number of Iterations....: 0
                                   (scaled)                 (unscaled)
Objective...............:   2.5999807855894869e+02    2.5866283240229580e+08
Dual infeasibility......:   1.9000013004444856e+01    1.8902436535875730e+07
Constraint violation....:   3.4933812241858782e+01    3.4933812241858782e+01
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   4.4750645232231720e+04    4.4520823814376411e+10
Overall NLP error.......:   4.4750645232231720e+04    4.4520823814376411e+10
Number of objective function evaluations             = 1
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 1
Number of inequality constraint evaluations          = 1
Number of equality constraint Jacobian evaluations   = 1
Number of inequality constraint Jacobian evaluations = 1
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 0.037
EXIT: Maximum Number of Iterations Exceeded.
```

Iteration 0 objective `2.5866283240229580e+08` &harr; `4974321.999640268`
Iteration 0 constraints `3.4933812241858782e+01` &harr; `1.328551330130685e-06`

Any ideas what could be wrong?

**Comment by brocksam** [comment] 2022-12-21 10:45
There's something happening with scaling in your problem as if you look at the Ipopt output, the scaled objective evaluation at the 0th iteration is 2.599...e+02, while the unscaled objective evaluation is 2.586...e+08. Can you please share what, if anything, you've done regarding scaling factors in your problem setup? Also, a minimal reproducer script for this would help others help diagnose what might be going on - I can't spot an obvious issue from just the information here.

Can you please confirm that you mean [https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables]() by class variables? Are these class variables you're setting yourself? Are you sure you're not overwriting any of the `Problem` classes internal attributes as this could explain unexpected behaviour?

**Comment by EmJay276** [comment] 2022-12-21 11:41
Thanks for the fast reply!
I am using instance variables, sorry for the misleading term.
I don't do any user scaling, default setting should be "gradient-based" due to the documentation.

The only options I use are
```
nlp.add_option('max_iter', 100)
nlp.add_option('warm_start_init_point', 'yes')
nlp.add_option('jac_d_constant', 'yes')
```
But I get the same results without these too.

The thing I'm concerned about is the unscaled objective evaluation which is 2.586...e+08 for the 0th iteration, but 4974321.99 for a manual evaluation of the objective function for the starting values x0.

I will try to build a minimal example.

**Comment by EmJay276** [comment] 2022-12-21 11:53
I can also repduce it with the https://github.com/mechmotum/cyipopt/blob/master/examples/hs071.py example.

Manual objective function evaluation
```
>>> nlp.__objective(x0)
16.0
```
Iteration 0 (unscaled objective function)
```
1.7346108150552816e+01
```

Should Iteration 0 not return the value of the "initial" objective function?

**Comment by brocksam** [comment] 2022-12-21 12:19
My current hypothesis on why you're seeing this:

In iteration zero, Ipopt evaluates the problem at your initial guess. Therefore, for the hs071 problem, you'd expect the unscaled objective function to evaluate to `16.0`. However, Ipopt appears to adjusts the supplied initial guess slightly in situations where the initial guess is at or close to the decision variable bounds. For the hs071 problem, lb <= x0 <= ub is `[1, 1, 1, 1] <= [1, 5, 5, 1] <= [5, 5, 5, 5]`. As all initial guess values are exactly equal to either the lower or upper bound, Ipopt adjusts the initial guess to `[1.00999999 4.96000005 4.96000005 1.00999999]` for the zeroth iteration evaluation.

Without knowing what your objective function implementation looks like, or what bounds you're using relative to your initial guess, I can't comment whether it's possible that this is the case for your problem.

**Comment by EmJay276** [comment] 2022-12-21 12:24
Ahhh I see. 
Yes, that’s probably the same for my problem here!
My initial guess is the solution of a very similar convex problem, which is (probably) right at the variable bounds.
Is it possible to tell ipopt to not adjust the initial guess?

For example, by adjusting `bound_push, bound_frac, ...`?

Currently my problem needs like 10-15 iterations to get "back" to the initial point before starting to improve from my initial solution.

**Comment by brocksam** [comment] 2022-12-21 12:33
> Is it possible to tell ipopt to not adjust the initial guess?

Unfortunately, I don't know I'm afraid.

> For example, by adjusting `bound_push, bound_frac, ...`?

I'm personally not familiar with any of these settings.

This question now might be better asked on one of the Ipopt channels. This [Ipopt documentation](https://coin-or.github.io/Ipopt/) suggests using the issue tracker or discussions on the [Ipopt GitHub](https://github.com/coin-or/Ipopt).

I will close this now as it appears to no longer be a CyIpopt-specific issue. Please feel free to reopen if you need further help.

**Closed by brocksam** 2022-12-21 12:33 UTC

**Comment by EmJay276** [comment] 2022-12-21 12:34
Yeah it seams not to be a cyipopt problem. Thanks for your help!
