### ISSUE TITLE
 'ipopt_wrapper.Problem' object has no attribute  '__jacobianstructure'

### ISSUE THREAD

**Issue by thanhndv212** [mechmotum/cyipopt#117] opened 2021-06-22 13:04 UTC
Hi, 
I have encountered this attribute error when run with python 3.6.

AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__jacobianstructure'
Exception ignored in: 'ipopt_wrapper.jacobian_cb'
AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__jacobianstructure'
Erreur de segmentation (core dumped)

I am not sure whether it is an issue with python 3.6 interface. Could you please help me resolve this?
I installed with pip, btw.

Thanks a lot.

**Comment by brocksam** [comment] 2021-06-22 13:37
Can you please provide further information? Which version of CyIpopt are you using? What code are you running to generate this error (minimal reproducer please)?

**Comment by thanhndv212** [comment] 2021-06-22 14:23
I use cyipopt 1.0.3.
I was trying to do hs071 problem. 

AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__jacobianstructure'
Exception ignored in: 'ipopt_wrapper.jacobian_cb'
AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__jacobianstructure'
AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__hessianstructure'
Exception ignored in: 'ipopt_wrapper.hessian_cb'
AttributeError: 'ipopt_wrapper.Problem' object has no attribute '__hessianstructure'
Option "hessian_approximation" is not chosen as "limited-memory", but eval_h returns false.
Exception of type: OPTION_INVALID in file "IpTNLPAdapter.cpp" at line 



 Exception message: eval_h is called but has not been implemented

**Comment by thanhndv212** [comment] 2021-06-22 16:13
I think it is something strange with the callback of jacobianstructure. it is not defined in the Problem class.
It works ok in my other computer with the similar setup except python 3.8.

**Comment by brocksam** [comment] 2021-06-22 17:40
I have tried and am unable to replicate the issue using Python 3.6, CyIpopt 1.0.3 and `examples/hs071.py`. It could we be something to do with how you have pip-installed CyIpopt (which is confusingly called Ipopt on PyPI). I'm not sure that we actually support installation using pip because of the issues with the Ipopt dependency not being included as part of CyIpopt but needing to be dynamically linked. The best solution is to try using conda to install, [as explained in the docs](https://cyipopt.readthedocs.io/en/stable/install.html).

**Comment by vacary** [comment] 2022-02-07 17:41
Hi,
Thanks for your great work interfacing Ipopt in Python.
I have also the same problem on Ubuntu 18.04 with python 3.6. Any update on this issue?

**Comment by moorepants** [comment] 2022-02-07 18:01
If this is something specific to Python 3.6, we probably won't fix it. Python 3.6 recently had its end of life: https://endoflife.date/python

Can you provide a reproducible example that shows the error on Python 3.7+?

**Comment by moorepants** [comment] 2023-04-06 11:38
No reproducible example has been provided here, so I'm closing this issue. Reopen if there is more info.

**Closed by moorepants** 2023-04-06 11:38 UTC
