### ISSUE TITLE
Printing IPOPT iterations

### ISSUE THREAD

**Issue by adkoele** [mechmotum/cyipopt#88] opened 2021-01-06 08:31 UTC
I am using cyipopt in Spyder (python 3.8), and everything seems to work fine, but I am not able to display the IPOPT iterations. I am using the following option:
`nlp.addOption(b'print_level', 5)`
However, I do not get any output from IPOPT during the optimization. Do you know how I can make sure that something is printed to see the progress?

**Comment by brocksam** [comment] 2021-01-06 08:58
Which version of CyIpopt are you using? And how did you install (e.g. using _conda_, from source etc.)?

Ipopt uses, by default, `print_level = 5` so without that line setting the print level explicitly you should still see Ipopt displaying the progress. If you remove you `addOption` line do you see any progress output from Ipopt? If so, what is it?

**Comment by adkoele** [comment] 2021-01-06 09:07
I am using CyIpopt version 0.1.7. I installed with conda a while ago, so I create an environment and installed. I removed the addOption line and it is the same.

**Comment by brocksam** [comment] 2021-01-06 09:20
CyIpopt 0.1.7 from _conda-forge_ was only available for Pythons 2.7, 3.5 and 3.6 (https://anaconda.org/conda-forge/cyipopt/files?version=0.1.7). There is a CyIpopt 0.2.0 available on _conda-forge_ for Python 3.8, are you able to update your environment to use this release and see if the problem persists?

**Comment by brocksam** [comment] 2021-01-06 09:35
Which functionality from CyIpopt are you using? Are you subclassing `problem` or are you using the `minimize_ipopt` function?

**Comment by brocksam** [comment] 2021-01-06 09:41
`minimize_ipopt` does seem to have `print_level = 0` as its default. As `minimize_ipopt` is a function its settings can be changed using the `options` kwarg (which accepts a dict), e.g. adapting the `rosen.py` example:

```python
from scipy.optimize import rosen, rosen_der
from ipopt import minimize_ipopt
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize_ipopt(rosen, x0, jac=rosen_der, options={b'print_level': 5})
print(res)
```

This will give you a console output like:

```
>>> res = minimize_ipopt(rosen, x0, jac=rosen_der, options={b"print_level": 5})

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.13.2, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        5
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.2982000e+02 0.00e+00 1.00e+02   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0673164e+02 0.00e+00 7.31e+01 -11.0 1.00e+02    -  1.00e+00 7.81e-03f  8
   2  2.3739758e+01 0.00e+00 2.23e+01 -11.0 2.57e-01    -  1.00e+00 1.00e+00f  1
   3  9.9126165e+00 0.00e+00 1.02e+01 -11.0 1.61e-01    -  1.00e+00 1.00e+00f  1
   4  4.8151331e+00 0.00e+00 1.53e+01 -11.0 1.69e-01    -  1.00e+00 1.00e+00f  1
   5  6.5761261e-01 0.00e+00 5.25e+00 -11.0 7.39e-02    -  1.00e+00 1.00e+00f  1
   6  8.6432701e-02 0.00e+00 1.68e+00 -11.0 3.82e-02    -  1.00e+00 1.00e+00f  1
   7  1.2712698e-04 0.00e+00 7.45e-02 -11.0 9.86e-03    -  1.00e+00 1.00e+00f  1
   8  2.3351201e-05 0.00e+00 1.03e-02 -11.0 2.29e-04    -  1.00e+00 1.00e+00f  1
   9  2.1123974e-05 0.00e+00 8.35e-04 -11.0 6.16e-05    -  1.00e+00 1.00e+00f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  2.1074406e-05 0.00e+00 7.66e-04 -11.0 6.82e-06    -  1.00e+00 1.00e+00f  1
  11  2.1000266e-05 0.00e+00 9.87e-04 -11.0 1.35e-05    -  1.00e+00 1.00e+00f  1
  12  2.0613174e-05 0.00e+00 5.59e-03 -11.0 2.50e-04    -  1.00e+00 1.00e+00f  1
  13  1.9348869e-05 0.00e+00 1.04e-02 -11.0 2.01e-03    -  1.00e+00 5.00e-01f  2
  14  1.9329308e-05 0.00e+00 1.26e-02 -11.0 3.15e-03    -  1.00e+00 1.56e-02f  7
  15  1.5980901e-05 0.00e+00 7.31e-03 -11.0 9.36e-05    -  1.00e+00 1.00e+00f  1
  16  8.7588882e-06 0.00e+00 3.32e-03 -11.0 1.49e-03    -  1.00e+00 1.00e+00f  1
  17  8.4268483e-06 0.00e+00 4.44e-03 -11.0 7.98e-02    -  1.00e+00 1.95e-03f 10
  18  4.2667942e-06 0.00e+00 5.65e-03 -11.0 7.91e-03    -  1.00e+00 1.00e+00f  1
  19  4.2510661e-06 0.00e+00 6.40e-03 -11.0 1.28e-01    -  1.00e+00 1.95e-03f 10
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  20  1.0656671e-07 0.00e+00 2.63e-03 -11.0 3.18e-03    -  1.00e+00 1.00e+00f  1
  21  7.0021561e-08 0.00e+00 1.79e-03 -11.0 2.72e-01    -  1.00e+00 9.77e-04f 11
  22  4.2626607e-09 0.00e+00 2.63e-04 -11.0 2.79e-04    -  1.00e+00 1.00e+00f  1
  23  9.2615608e-10 0.00e+00 1.91e-04 -11.0 6.70e-03    -  1.00e+00 3.91e-03f  9
  24  8.6350087e-10 0.00e+00 2.14e-04 -11.0 1.64e-04    -  1.00e+00 1.56e-02f  7
  25  5.0272749e-12 0.00e+00 1.60e-05 -11.0 2.04e-05    -  1.00e+00 1.00e+00f  1
  26  3.5286100e-12 0.00e+00 1.25e-05 -11.0 1.13e-05    -  1.00e+00 7.81e-03f  8
  27  7.6301259e-17 0.00e+00 3.30e-08 -11.0 1.13e-06    -  1.00e+00 1.00e+00f  1
  28  7.0717983e-17 0.00e+00 3.39e-08 -11.0 1.50e-06    -  1.00e+00 1.56e-02f  7
  29  6.7693423e-17 0.00e+00 3.11e-08 -11.0 2.05e-08    -  1.00e+00 6.25e-02f  5
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  30  3.1009091e-17 0.00e+00 3.94e-08 -11.0 6.67e-08    -  1.00e+00 2.50e-01f  3
  31  2.2704253e-17 0.00e+00 1.96e-08 -11.0 2.72e-06    -  1.00e+00 9.77e-04f 11
  32  2.6866813e-21 0.00e+00 2.72e-10 -11.0 6.72e-09    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 32

                                   (scaled)                 (unscaled)
Objective...............:   5.2128081684565383e-22    2.6866813300225001e-21
Dual infeasibility......:   2.7206754074605128e-10    1.4022361050051486e-09
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   2.7206754074605128e-10    1.4022361050051486e-09


Number of objective function evaluations             = 170
Number of objective gradient evaluations             = 33
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.042
Total CPU secs in NLP function evaluations           =      0.009

EXIT: Optimal Solution Found.
```

**Comment by adkoele** [comment] 2021-01-06 09:46
I am constructing a problem: 

`nlp = ipopt.problem(n=len(X0),
                        m=len(cl),
                        problem_obj=pendulum(params),
                        lb=L,
                        ub=U,
                        cl=cl,
                        cu=cu)`

When I run:
`from scipy.optimize import rosen, rosen_der
from ipopt import minimize_ipopt
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize_ipopt(rosen, x0, jac=rosen_der, options={b'print_level': 5})
print(res)`

I get the following output:
`
     fun: 2.1519764955882358e-18
    info: {'x': array([1., 1., 1., 1., 1.]), 'g': array([], dtype=float64), 'obj_val': 2.1519764955882358e-18, 'mult_g': array([], dtype=float64), 'mult_x_L': array([0., 0., 0., 0., 0.]), 'mult_x_U': array([0., 0., 0., 0., 0.]), 'status': 0, 'status_msg': b'Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).'}
 message: b'Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).'
    nfev: 200
     nit: 37
    njev: 39
  status: 0
 success: True
       x: array([1., 1., 1., 1., 1.])`

**Comment by brocksam** [comment] 2021-01-06 09:52
Can you please provide full details of your `conda` virtual environment? I can't currently replicate the bug locally so can't debug...

**Comment by adkoele** [comment] 2021-01-06 09:55
How can I best send you that?

**Comment by brocksam** [comment] 2021-01-06 09:58
If you run `conda list` within your console with the appropriate conda environment activated then you will get a print out of all of the packages you have installed and related details. If you could then copy-paste that here I'll be able to try to replicate the env.

**Comment by adkoele** [comment] 2021-01-06 10:12
Thanks! Here is the list:
# Name                    Version                   Build  Channel                                                      
alabaster                 0.7.12                     py_0                                                               
argh                      0.26.2                   py38_0                                                               
astroid                   2.4.2                    py38_0                                                              
async_generator           1.10                       py_0                                                               
atomicwrites              1.4.0                      py_0                                                              
attrs                     20.3.0             pyhd3eb1b0_0                                                               
autopep8                  1.5.4                      py_0                                                               
babel                     2.9.0              pyhd3eb1b0_0                                                               
backcall                  0.2.0                      py_0                                                               
bcrypt                    3.2.0            py38he774522_0                                                               
blas                      1.0                         mkl                                                               
bleach                    3.2.1                      py_0                                                               
brotlipy                  0.7.0           py38h2bbff1b_1003                                                             
ca-certificates           2020.10.14                    0                                                               
certifi                   2020.11.8        py38haa95532_0                                                               
cffi                      1.14.4           py38hcd4344a_0                                                               
chardet                   3.0.4           py38haa95532_1003                                                             
cloudpickle               1.6.0                      py_0                                                               
colorama                  0.4.4                      py_0                                                               
cryptography              3.2.1            py38hcd4344a_1                                                               
cycler                    0.10.0                   py38_0                                                               
cyipopt                   0.1.7                    py38_2    pycalphad                                                  
decorator                 4.4.2                      py_0                                                               
defusedxml                0.6.0                      py_0                                                               
diff-match-patch          20200713                   py_0                                                               
docutils                  0.16                     py38_1                                                               
entrypoints               0.3                      py38_0                                                               
flake8                    3.8.4                      py_0                                                               
freetype                  2.10.4               hd328e21_0                                                               
future                    0.18.2                   py38_1                                                               
icc_rt                    2019.0.0             h0cc432a_1                                                               
icu                       58.2                 ha925a31_3                                                               
idna                      2.10                       py_0                                                               
imagesize                 1.2.0                      py_0                                                               
importlib-metadata        2.0.0                      py_1                                                               
importlib_metadata        2.0.0                         1                                                               
intel-openmp              2020.2                      254                                                               
intervaltree              3.1.0                      py_0                                                               
ipopt                     3.12.8               h8b5faf3_1    pycalphad                                                  
ipykernel                 5.3.4            py38h5ca1d4c_0                                                               
ipython                   7.19.0           py38hd4e2768_0                                                              
 ipython_genutils          0.2.0              pyhd3eb1b0_1                                                               
isort                     5.6.4                      py_0                                                               
jedi                      0.17.1                   py38_0                                                               
jinja2                    2.11.2                     py_0                                                              
 jpeg                      9b                   hb83a4c4_2                                                               
jsonschema                3.2.0                      py_2                                                               
jupyter_client            6.1.7                      py_0                                                               
jupyter_core              4.7.0            py38haa95532_0                                                               
jupyterlab_pygments       0.1.2                      py_0                                                               
keyring                   21.4.0                   py38_1                                                               
kiwisolver                1.3.0            py38hd77b12b_0                                                               
lazy-object-proxy         1.4.3            py38he774522_0                                                               
libpng                    1.6.37               h2a8f88b_0                                                               
libsodium                 1.0.18               h62dcd97_0                                                               
libspatialindex           1.9.3                h33f27b4_0                                                               
libtiff                   4.1.0                h56a325e_1                                                               
lz4-c                     1.9.2                hf4a77e7_3                                                               
m2w64-gcc-libgfortran     5.3.0                         6                                                               
m2w64-gcc-libs            5.3.0                         7                                                               
m2w64-gcc-libs-core       5.3.0                         7                                                               
m2w64-gmp                 6.1.0                         2                                                               
m2w64-libwinpthread-git   5.0.0.4634.697f757               2                                                            
m2w64-openblas            0.2.19                        1                                                               
markupsafe                1.1.1            py38he774522_0                                                               
matplotlib                3.3.2                         0                                                               
matplotlib-base           3.3.2            py38hba9282a_0                                                               
mccabe                    0.6.1                    py38_1                                                               
mistune                   0.8.4           py38he774522_1000                                                             
mkl                       2020.2                      256                                                               
mkl-service               2.3.0            py38h196d8e1_0                                                               
mkl_fft                   1.2.0            py38h45dec08_0                                                               
mkl_random                1.1.1            py38h47e9c7a_0                                                               
msys2-conda-epoch         20160418                      1                                                               
mumps                     5.0.2              hd492a52_203    pycalphad                                                  
nbclient                  0.5.1                      py_0                                                               
nbconvert                 6.0.7                    py38_0                                                               
nbformat                  5.0.8                      py_0                                                               
nest-asyncio              1.4.3              pyhd3eb1b0_0                                                               
numpy                     1.19.2           py38hadc3359_0                                                               
numpy-base                1.19.2           py38ha3acd2a_0                                                               
numpydoc                  1.1.0              pyhd3eb1b0_1                                                               
olefile                   0.46                       py_0                                                               
openssl                   1.1.1h               he774522_0                                                               
packaging                 20.7               pyhd3eb1b0_0                                                               
pandoc                    2.11                 h9490d1a_0                                                               
pandocfilters             1.4.3            py38haa95532_1                                                               
paramiko                  2.7.2                      py_0                                                               
parso                     0.7.0                      py_0                                                               
pathtools                 0.1.2                      py_1                                                               
pexpect                   4.8.0              pyhd3eb1b0_3                                                               
pickleshare               0.7.5           pyhd3eb1b0_1003                                                               
pillow                    8.0.1            py38h4fa10fc_0                                                               
pip                       20.3             py38haa95532_0                                                               
pluggy                    0.13.1                   py38_0                                                               
prompt-toolkit            3.0.8                      py_0                                                               
psutil                    5.7.2            py38he774522_0                                                               
ptyprocess                0.6.0              pyhd3eb1b0_2                                                               
pycodestyle               2.6.0                      py_0                                                               
pycparser                 2.20                       py_2                                                               
pydocstyle                5.1.1                      py_0                                                               
pyflakes                  2.2.0                      py_0                                                               
pygments                  2.7.2              pyhd3eb1b0_0                                                               
pylint                    2.6.0                    py38_0                                                               
pynacl                    1.4.0            py38h62dcd97_1                                                               
pyopenssl                 20.0.0             pyhd3eb1b0_1                                                               
pyparsing                 2.4.7                      py_0                                                               
pyqt                      5.9.2            py38ha925a31_4                                                               
pyrsistent                0.17.3           py38he774522_0                                                               
pysocks                   1.7.1            py38haa95532_0                                                               
python                    3.8.5                h5fd99cc_1                                                               
python-dateutil           2.8.1                      py_0                                                               
python-jsonrpc-server     0.4.0                      py_0                                                               
python-language-server    0.35.1                     py_0                                                              
pytz                      2020.4             pyhd3eb1b0_0                                                              
pywin32                   227              py38he774522_1                                                               
pywin32-ctypes            0.2.0                 py38_1000                                                               
pyyaml                    5.3.1            py38he774522_1                                                               
pyzmq                     20.0.0           py38hd77b12b_1                                                               
qdarkstyle                2.8.1                      py_0                                                               
qt                        5.9.7            vc14h73c81de_0                                                               
qtawesome                 1.0.1                      py_0                                                               
qtconsole                 4.7.7                      py_0                                                               
qtpy                      1.9.0                      py_0                                                               
requests                  2.25.0             pyhd3eb1b0_0                                                               
rope                      0.18.0                     py_0                                                               
rtree                     0.9.4            py38h21ff451_1                                                               
scipy                     1.5.2            py38h14eb087_0                                                               
setuptools                50.3.2           py38haa95532_2                                                               
sip                       4.19.13          py38ha925a31_0                                                               
six                       1.15.0           py38haa95532_0                                                               
snowballstemmer           2.0.0                      py_0                                                               
sortedcontainers          2.3.0              pyhd3eb1b0_0                                                               
sphinx                    3.2.1                      py_0                                                               
sphinxcontrib-applehelp   1.0.2                      py_0                                                               
sphinxcontrib-devhelp     1.0.2                      py_0                                                               
sphinxcontrib-htmlhelp    1.0.3                      py_0                                                               
sphinxcontrib-jsmath      1.0.1                      py_0                                                               
sphinxcontrib-qthelp      1.0.3                      py_0                                                               
sphinxcontrib-serializinghtml 1.1.4                      py_0                                                           
spyder                    4.1.5                    py38_0                                                               
spyder-kernels            1.9.4                    py38_0                                                               
sqlite                    3.33.0               h2a8f88b_0                                                               
testpath                  0.4.4                      py_0                                                               
tk                        8.6.10               he774522_0                                                               
toml                      0.10.1                     py_0                                                               
tornado                   6.1              py38h2bbff1b_0                                                               
traitlets                 5.0.5                      py_0                                                               
ujson                     4.0.1            py38ha925a31_0                                                               
urllib3                   1.25.11                    py_0                                                               
vc                        14.1                 h0510ff6_4                                                               
vs2015_runtime            14.16.27012          hf0eaf9b_3                                                               
watchdog                  0.10.4           py38haa95532_0                                                               
wcwidth                   0.2.5                      py_0                                                               
webencodings              0.5.1                    py38_1                                                               
wheel                     0.36.0             pyhd3eb1b0_0                                                               
win_inet_pton             1.1.0            py38haa95532_0                                                               
wincertstore              0.2                      py38_0                                                               
wrapt                     1.11.2           py38he774522_0                                                               
xz                        5.2.5                h62dcd97_0                                                               
yaml                      0.2.5                he774522_0                                                              
yapf                      0.30.0                     py_0                                                               
zeromq                    4.3.3                ha925a31_3                                                               
zipp                      3.4.0              pyhd3eb1b0_0                                                               
zlib                      1.2.11               h62dcd97_4                                                               
zstd                      1.4.5                h04227a9_0

**Comment by moorepants** [comment] 2021-01-06 11:05
Anne, you likely don't need packages from pycalphad (maybe you accidentally added or installed from that channel?)

**Comment by moorepants** [comment] 2021-01-06 11:11
I just tried cyipopt 0.3.0 with Spyder running one of the examples and it does print ipopt's results to the console:

![image](https://user-images.githubusercontent.com/276007/103762246-3f843c00-5018-11eb-9777-0788ee96b2c1.png)

**Comment by adkoele** [comment] 2021-01-06 12:16
Thanks for the help! I did indeed install from there, because that was the option that I found to install. I was not able to install as follows: `(cyipopt) $ conda install cyipopt --channel conda-forge`

I got the following error:
PackagesNotFoundError: The following packages are not available from current channels:

  - cyipopt

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

Should I add a channel? Otherwise, to install from the source seems like it requires much more time, which I don't have right now.

**Comment by moorepants** [comment] 2021-01-06 12:21
Ah yes, this is because we haven't released windows builds on conda forge yet due to: https://github.com/conda-forge/cyipopt-feedstock/pull/25 not being merged. Cyipopt 0.3.0 introduces working windows builds (which is very recent). The pycalphad people must have a windows build of version 0.1.7. It's possible that 0.1.7 doesn't print the output for some reason.

Some possible solutions:

- Wait till we get https://github.com/conda-forge/cyipopt-feedstock/pull/25 merged.
- Install ipopt from conda forge and then install cyipopt from source. This requires a working compiler and cython.

We could also merge https://github.com/conda-forge/cyipopt-feedstock/pull/25 by forcing cyipopt to use the netlib versions of blas/lapack (which are slower but functional).

**Comment by moorepants** [comment] 2021-01-06 12:33
> Otherwise, to install from the source seems like it requires much more time, which I don't have right now.

Yes, it takes more time, but we've had other windows users get it installed without too much trouble recently. So maybe it isn't much time.

**Comment by moorepants** [comment] 2021-01-06 13:19
I just tried cyipopt 0.1.7 on linux in spyder and the output also works:
![image](https://user-images.githubusercontent.com/276007/103772638-1f5d7880-502a-11eb-87b5-8456f8593a70.png)

So, either the output doesn't work on Windows in Spyder or the pycalphad build of cyipopt changes something.

**Comment by bocklund** [comment] 2021-01-06 17:45
@richardotis packaged the pycalphad channel's build of cyipopt. That build does not change any cyipopt source AFAIK, only the build scripts of cyipopt and it's dependencies to get things to compile correctly (some discussion in https://github.com/conda-forge/cyipopt-feedstock/pull/16).


I am able to reproduce this issue on Windows, Python 3.7 and the pycalphad channel's cyipopt 1.7 in Spyder, using the snippet that @brocksam put together:

```python
from scipy.optimize import rosen, rosen_der
from ipopt import minimize_ipopt
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize_ipopt(rosen, x0, jac=rosen_der, options={b'print_level': 5})
print(res)
```

If you run this script from the command line (e.g. an Anaconda Prompt), then you see all the ipopt output that you would expect.

Running the same script in the IPython console of Spyder does not produce the output in Spyder's console.

However, if you start Spyder from an Anaconda Prompt (rather than clicking on the Spyder icon in the Windows Start Menu GUI), then I can see all the ipopt output in the Anaconda Prompt (rather than the IPython console within Spyder). It seems like the kernel used by Spyder is not correctly picking up the output and displaying it. This is/was a known Spyder issue, which appears to have been discussed a few places, such as https://github.com/spyder-ide/spyder/issues/3777 and https://github.com/spyder-ide/spyder/issues/9759.

If this is the underlying issue, the bug should reproduce in Spyder on Windows even if cyipopt was installed from source (though I have not verified this).

**Comment by donboyd5** [comment] 2021-01-06 17:50
FWIW I installed cyipopt from source, in Windows, about 3 months ago (i.e.,
not latest version) and found that this is exactly what I got. It wasn't an
impediment, of course. And if I wanted to see things in the Spyder console
I used the callback approach.

Don

**Comment by moorepants** [comment] 2021-01-06 18:16
@adkoele So this looks like an issue with Spyder. There are two work arounds presented:

1. Use the callback `problem.intermediate()` to display what you want with python `print()` calls (see https://cyipopt.readthedocs.io/en/latest/tutorial.html for an example), or
2. Start spyder via the Anaconda prompt by typing `spyder` and you'll see ipopt displayed in that window when you execute things in spyder.

**Comment by moorepants** [comment] 2021-01-06 18:34
This won't solve this issue, but I finally got cyipopt to build on all OSes for version 0.3.0 for conda forge. This is merged:

https://github.com/conda-forge/cyipopt-feedstock/pull/26

So, in an hour or so you should be able to `conda install -c conda-forge cyipopt` to get version 0.3.0 on Windows.

**Comment by donboyd5** [comment] 2021-01-06 18:44
Thanks so much. Ipopt is a great solver and a pain to set up in Windows. I
really appreciate this. I am switching over to linux soon, in part because
I want to be able to use the HSL linear solvers with it and have not been
able to get them to work in Windows except by compiling with Ipopt from
source in an R arrangement and would like to use with python. Again, thanks.

**Comment by moorepants** [comment] 2021-01-06 18:49
We need some instructions for using HSL solvers with the conda forge build on all OSes. It theorectically should be as easy as dropping the files into the right directory.

**Comment by moorepants** [comment] 2023-04-07 05:24
This should now be resolved with the conda forge windows builds and HSL instructions.

**Closed by moorepants** 2023-04-07 05:24 UTC
